### ISSUE TITLE
Huobi missing from IExchangeRestClient

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/CryptoClients.Net#1]
Hi JKorf,
I recently try your new librairy (CryptoClient) and notice that Huobi is missing in the IExchangeRestClient interface, but present in the implementation.

Is this a feature, or a bug ?

Thanks
Eric

**Comment by JKorf** [comment]
Hi Eric, thanks for sharing your observation. It's not a feature; I'll fix it in next version. But as I'm currently on holiday that will be in all little while.

Let me know if you have any other feedback or issues

**Comment by JKorf** [comment]
Fixed in the latest version
